services:
  - type: web
    name: stock-management-app
    runtime: docker
    dockerfilePath: ./Stock-app-backend/Dockerfile
    buildCommand: cd Stock-app-backend && mvn clean package -DskipTests
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: stock-db
          property: connectionString
      - key: JAVA_OPTS
        value: "-Xms128m -Xmx400m -XX:+UseSerialGC"
    
databases:
  - name: stock-db
    databaseName: stockdb
    user: stockuser
    plan: free